### ISSUE TITLE
Failed to enable IDENTd: listen tcp 127.0.0.1:113: bind: permission denied

### ISSUE THREAD

**Issue by joeblew99** [tulir/mauirc-server#2]
```

x-MacBook-Pro:mauirc-server apple$ ./mauirc-server --config=./package/etc/mauirc
[11:40:46 29.08.2016] [INFO] Initializing mauIRC Server 2.0.0
[11:40:46 29.08.2016] [FATAL] Failed to enable IDENTd: listen tcp 127.0.0.1:113: bind: permission denied

```

i tried changing the port. No dice.

**Comment by joeblew99** [comment]
Its looking for an Ident server i realised :)

So do i need to download one and start it up on that port ?

**Comment by tulir** [comment]
mauIRC has an integrated IDENT server (it was easier to make that way).  Most IRC networks don't require IDENT (unless you have a lot of users from the same IP), but if you want to you can use it without root for mauIRC by using something to proxy the IDENT requests to mauIRC.

Here's an example Nginx config that goes in the root of the nginx.conf file (not in the `http` section)

``` nginx
stream {
    upstream mauircident {
        server 127.0.0.1:1113; # mauirc-server IDENT ip:port
    }

    server {
        listen      113;
        listen      [::]:113; # ipv6 (optional)
        proxy_pass  mauircident;
    }
}
```

**Comment by joeblew99** [comment]
I could just set it to false for now, in the config?

  "ident": {
    "enabled": false,
    "ip": "127.0.0.1",
    "port": 113
  },

so i can work forward and come back to that

**Comment by tulir** [comment]
Yeah, as I said most IRC networks don't require IDENT. Joining a network may take a few seconds longer because they might still check for IDENT.

**Comment by joeblew99** [comment]
ok thanks.

i got it running on mysql.

My intent it to play with gopherjs, and i just wanted to get the server going so i had something behind it all.
